algoritmo "Atividade 8"

var

 i: inteiro
 
inicio

       Escreval ("Os números pares são: ")
       Para i de 1 ate 100 faca
             se ((i mod 2)= 0)entao
                se(i <> 100)entao
                     escreval(i)
                     senao
                     escreval(i)
                     fimse
                     fimse
                     fimpara

fimalgoritmo
